// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum BufferMask {

		FrontLeftBufferBit = 1 << 0,
		FrontRightBufferBit = 1 << 1,
		BackLeftBufferBit = 1 << 2,
		BackRightBufferBit = 1 << 3,
		AuxBuffersBit = 1 << 4,
		DepthBufferBit = 1 << 5,
		StencilBufferBit = 1 << 6,
		AccumBufferBit = 1 << 7,
	}
#endregion
}
