// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum ConfigMode {

		Rgb = 0,
		Rgba = 0,
		Index = 1 << 0,
		Single = 0,
		Double = 1 << 1,
		Stereo = 1 << 2,
		Alpha = 1 << 3,
		Depth = 1 << 4,
		Stencil = 1 << 5,
		Accum = 1 << 6,
		Multisample = 1 << 7,
	}
#endregion
}
