// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum ConfigAttrib {

		UseGl = 1,
		BufferSize = 2,
		Level = 3,
		Rgba = 4,
		Doublebuffer = 5,
		Stereo = 6,
		AuxBuffers = 7,
		RedSize = 8,
		GreenSize = 9,
		BlueSize = 10,
		AlphaSize = 11,
		DepthSize = 12,
		StencilSize = 13,
		AccumRedSize = 14,
		AccumGreenSize = 15,
		AccumBlueSize = 16,
		AccumAlphaSize = 17,
		ConfigCaveat = 0x20,
		XVisualType = 0x22,
		TransparentType = 0x23,
		TransparentIndexValue = 0x24,
		TransparentRedValue = 0x25,
		TransparentGreenValue = 0x26,
		TransparentBlueValue = 0x27,
		TransparentAlphaValue = 0x28,
		DrawableType = 0x8010,
		RenderType = 0x8011,
		XRenderable = 0x8012,
		FbconfigId = 0x8013,
		MaxPbufferWidth = 0x8016,
		MaxPbufferHeight = 0x8017,
		MaxPbufferPixels = 0x8018,
		VisualId = 0x800B,
		Screen = 0x800C,
		SampleBuffers = 100000,
		Samples = 100001,
	}
#endregion
}
