// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum ConfigCaveat {

		ConfigCaveatDontCare = 0x7FFFFFFF,
		ConfigCaveatNone = 0x8000,
		SlowConfig = 0x8001,
		NonConformantConfig = 0x800D,
	}
#endregion
}
