// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum ConfigError {

		BadScreen = 1,
		BadAttribute = 2,
		NoExtension = 3,
		BadVisual = 4,
		BadContext = 5,
		BadValue = 6,
		BadEnum = 7  ,
	}
#endregion
}
