// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum DebugFlag {

		Misc = 1 << 0,
		Func = 1 << 1,
		Impl = 1 << 2,
	}
#endregion
}
