// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum DrawableType {

		Window = 0x8022,
		Pbuffer = 0x8023,
	}
#endregion
}
