// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum DrawableTypeMask {

		WindowBit = 1 << 0,
		PixmapBit = 1 << 1,
		PbufferBit = 1 << 2,
	}
#endregion
}
