// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Draw {

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_tetrahedron(bool solid);

		public static void Tetrahedron(bool solid) {
			gdk_gl_draw_tetrahedron(solid);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_cube(bool solid, double size);

		public static void Cube(bool solid, double size) {
			gdk_gl_draw_cube(solid, size);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_dodecahedron(bool solid);

		public static void Dodecahedron(bool solid) {
			gdk_gl_draw_dodecahedron(solid);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_cone(bool solid, double _base, double height, int slices, int stacks);

		public static void Cone(bool solid, double _base, double height, int slices, int stacks) {
			gdk_gl_draw_cone(solid, _base, height, slices, stacks);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_teapot(bool solid, double scale);

		public static void Teapot(bool solid, double scale) {
			gdk_gl_draw_teapot(solid, scale);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_sphere(bool solid, double radius, int slices, int stacks);

		public static void Sphere(bool solid, double radius, int slices, int stacks) {
			gdk_gl_draw_sphere(solid, radius, slices, stacks);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_torus(bool solid, double inner_radius, double outer_radius, int nsides, int rings);

		public static void Torus(bool solid, double inner_radius, double outer_radius, int nsides, int rings) {
			gdk_gl_draw_torus(solid, inner_radius, outer_radius, nsides, rings);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_icosahedron(bool solid);

		public static void Icosahedron(bool solid) {
			gdk_gl_draw_icosahedron(solid);
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern void gdk_gl_draw_octahedron(bool solid);

		public static void Octahedron(bool solid) {
			gdk_gl_draw_octahedron(solid);
		}

#endregion
	}
}
