// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;

#region Autogenerated code
	public interface Drawable : GLib.IWrapper {

		GdkGL.Config GlConfig { 
			get;
		}
		void WaitGdk();
		void WaitGl();
		bool GlBegin(GdkGL.Context glcontext);
		bool IsDoubleBuffered { 
			get;
		}
		void GetSize(out int width, out int height);
		bool MakeCurrent(GdkGL.Context glcontext);
		void GlEnd();
		void SwapBuffers();
	}

	[GLib.GInterface (typeof (DrawableAdapter))]
	public interface DrawableImplementor : GLib.IWrapper {

	}
#endregion
}
