// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum DrawableAttrib {

		PreservedContents = 0x801B,
		LargestPbuffer = 0x801C,
		Width = 0x801D,
		Height = 0x801E,
		EventMask = 0x801F,
	}
#endregion
}
