// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum EventMask {

		Mask = 1 << 27,
	}
#endregion
}
