// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum EventType {

		Damaged = 0x8020,
		Saved = 0x8021,
	}
#endregion
}
