// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGLSharp {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[UnmanagedFunctionPointer (CallingConvention.Cdecl)]
	internal delegate void ProcNative();

	internal class ProcInvoker {

		ProcNative native_cb;
		IntPtr __data;
		GLib.DestroyNotify __notify;

		~ProcInvoker ()
		{
			if (__notify == null)
				return;
			__notify (__data);
		}

		internal ProcInvoker (ProcNative native_cb) : this (native_cb, IntPtr.Zero, null) {}

		internal ProcInvoker (ProcNative native_cb, IntPtr data) : this (native_cb, data, null) {}

		internal ProcInvoker (ProcNative native_cb, IntPtr data, GLib.DestroyNotify notify)
		{
			this.native_cb = native_cb;
			__data = data;
			__notify = notify;
		}

		internal GdkGL.Proc Handler {
			get {
				return new GdkGL.Proc(InvokeNative);
			}
		}

		void InvokeNative ()
		{
			native_cb ();
		}
	}

	internal class ProcWrapper {

		public void NativeCallback ()
		{
			try {
				managed ();
				if (release_on_call)
					gch.Free ();
			} catch (Exception e) {
				GLib.ExceptionManager.RaiseUnhandledException (e, false);
			}
		}

		bool release_on_call = false;
		GCHandle gch;

		public void PersistUntilCalled ()
		{
			release_on_call = true;
			gch = GCHandle.Alloc (this);
		}

		internal ProcNative NativeDelegate;
		GdkGL.Proc managed;

		public ProcWrapper (GdkGL.Proc managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new ProcNative (NativeCallback);
		}

		public static GdkGL.Proc GetManagedDelegate (ProcNative native)
		{
			if (native == null)
				return null;
			ProcWrapper wrapper = (ProcWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
#endregion
}
