// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Global {

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern bool gdk_gl_init_check(out int argc, IntPtr argv);

		public static bool InitCheck(out int argc, string argv) {
			IntPtr native_argv = GLib.Marshaller.StringToPtrGStrdup(argv);
			bool raw_ret = gdk_gl_init_check(out argc, native_argv);
			bool ret = raw_ret;
			GLib.Marshaller.Free (native_argv);
			return ret;
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern bool gdk_gl_parse_args(out int argc, IntPtr argv);

		public static bool ParseArgs(out int argc, string argv) {
			IntPtr native_argv = GLib.Marshaller.StringToPtrGStrdup(argv);
			bool raw_ret = gdk_gl_parse_args(out argc, native_argv);
			bool ret = raw_ret;
			GLib.Marshaller.Free (native_argv);
			return ret;
		}

		[DllImport("libgdkglext-win32-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gdk_gl_get_GL_ATI_vertex_attrib_array_object();

	/*	public static GdkGL._GL_ATIVertexAttribArrayObject Get_GL_ATIVertexAttribArrayObject() {
			IntPtr raw_ret = gdk_gl_get_GL_ATI_vertex_attrib_array_object();
			GdkGL._GL_ATIVertexAttribArrayObject ret = GdkGL._GL_ATIVertexAttribArrayObject.New (raw_ret);
			return ret;
		}   */

#endregion
	}
}
