// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum PbufferAttrib {

		PreservedContents = 0x801B,
		LargestPbuffer = 0x801C,
		Height = 0x8040,
		Width = 0x8041,
	}
#endregion
}
