// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum RenderType {

		RgbaType = 0x8014,
		ColorIndexType = 0x8015,
	}
#endregion
}
