// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GdkGL {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum VisualType {

		VisualTypeDontCare = 0x7FFFFFFF,
		TrueColor = 0x8002,
		DirectColor = 0x8003,
		PseudoColor = 0x8004,
		StaticColor = 0x8005,
		GrayScale = 0x8006,
		StaticGray = 0x8007,
	}
#endregion
}
